import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Header from "@/components/Header";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang='es' suppressHydrationWarning>
         <body className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
            <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
               <div className='bg-background'>
                  <Header></Header>
                  <main className='container mx-auto px-6 min-h-screen'>{children}</main>
                  <footer className='border-t w-full bg-card'>
                     <div className='container mx-auto py-4 text-center text-sm'>© 2025 Next.js Demo</div>
                  </footer>
               </div>
               <Toaster />
            </ThemeProvider>
         </body>
      </html>
   );
}
