import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { ModeToggle } from "@/components/ui/mode-toggle";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang='es' suppressHydrationWarning>
         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
               <div className='min-h-screen bg-background'>
                  <header className='border-b'>
                     <div className='container flex h-16 items-center px-4'>
                        <nav className='flex items-center space-x-4 lg:space-x-6'>
                           <Button variant='link' asChild>
                              <Link href='/'>Inicio</Link>
                           </Button>
                           <Button variant='link' asChild>
                              <Link href='/blog'>blog</Link>
                           </Button>
                           <Button variant='link' asChild>
                              <Link href='/dashboard'>dashboard</Link>
                           </Button>
                        </nav>
                        <div className='ml-auto'>
                           <ModeToggle />
                        </div>
                     </div>
                  </header>
                  <main className='container py-6'>{children}</main>
                  <footer className='border-t'>
                     <div className='container py-4 text-center text-sm'>© 2025 Next.js Demo</div>
                  </footer>
               </div>
            </ThemeProvider>
         </body>
      </html>
   );
}
